package krimeano.aoc2024.days.day08;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

class Day8x1Test {
    protected static final String TEST_INPUT = """
            ............
            ........0...
            .....0......
            .......0....
            ....0.......
            ......A.....
            ............
            ............
            ........A...
            .........A..
            ............
            ............
            """;

    @Test
    void solve() {
        assertEquals(14, new Day8x1(true).solve(TEST_INPUT));
    }
}
